CREATE OR REPLACE VIEW V_OE_REPORT AS
SELECT 
	b.NAME as BRAND_NAME,
	f.NAME as FILTER_NAME,
	o.NAME as OE_NAME
FROM filter f
LEFT OUTER JOIN FILTERSANDOES fao ON fao.FILTERID = f.ID
LEFT OUTER JOIN OE o ON o.ID = fao.OEID
LEFT OUTER JOIN BRAND b ON b.ID = o.BRANDID
WHERE fao.ID IS NOT NULL AND o.ID IS NOT NULL AND b.ID IS NOT NULL
ORDER BY b.NAME, f.NAME@

CREATE OR REPLACE VIEW V_OE_REPORT_GW AS
SELECT 
	b.NAME as BRAND_NAME,
	f.NAME as FILTER_NAME,
	o.NAME as OE_NAME
FROM filter f
LEFT OUTER JOIN FILTERSANDOES fao ON fao.FILTERID = f.ID
LEFT OUTER JOIN OE o ON o.ID = fao.OEID
LEFT OUTER JOIN BRAND b ON b.ID = o.BRANDID
WHERE fao.ID IS NOT NULL AND o.ID IS NOT NULL AND b.ID IS NOT NULL AND f.ONSITE = 1
ORDER BY b.NAME, f.NAME@