select
	FIFOG_GRUPPE as ID,
	FIFOG_PDARTG as FILTERTYPECODE,
	FIFOG_TITEL as NAME,
	FIFOG_A as APARAM,
	FIFOG_B as BPARAM,
	FIFOG_C as CPARAM,
	FIFOG_D as DPARAM,
	FIFOG_E as EPARAM,
	FIFOG_F as FPARAM,
	FIFOG_G as GPARAM,
	FIFOG_H as HPARAM,
	FIFOG_UGV as BPPARAM,
	FIFOG_RSV as NRPARAM
from SDAETOKFIFOG where FIFOG_SPRAS = 'R'